- name: add apt repository for golang
  apt_repository: repo='ppa:ubuntu-lxc/lxd-stable'
  become: yes

- name: add apt repository for zeal
  apt_repository: repo='ppa:zeal-developers/ppa'
  become: yes

- name: apt-get update
  apt: update_cache=yes
  become: yes

- name: apt-get upgrade
  apt: upgrade=dist
  become: yes

- name: install packages
  apt: name="{{ item.name }}" state="{{ item.state|default("latest") }}"
  with_items: "{{apt_packages}}"
  become: yes
