dot_vscode: ~/.config/Code/User

packages:
  - ms-python.python
  - ms-vscode.go
  - hiro-sun.vscode-emacs
  - christian-kohler.path-intellisense
  - dbaeumer.vscode-eslint
  - ms-vscode.cpptools
  - waderyan.gitblame
  - ericmccarthy.vs-code-mark-point
  - deerawan.vscode-dash
  - eg2.tslint
  - msjsdiag.debugger-for-chrome
  - esbenp.prettier-vscode
  - coenraads.bracket-pair-colorizer
